language: python
python:
  - "2.7"

install:
  - pip install tinkerer
  - pip install sphinxjp.themes.tinkerturquoise

env:
  global:
  - ENCRYPTION_LABEL: "11a378f8e3b8"
  - COMMIT_AUTHOR_EMAIL: "micviklui@gmail.com"

script:
  - tinker -b

after_success:
  - bash ./deploy.sh

notifications:
  email:
    recipients:
      - micviklui@gmail.com
    on_success: change # option [alway|never|change]
    on_failure: always
